"""In-memory PostgreSQL double for vault target tests.

Interprets only the statement shapes generated by vault targets:

- ``SELECT cols FROM t [WHERE pk > $1] ORDER BY pk LIMIT $n``
- ``UPDATE t SET col = $n | col = NOW() | col = COALESCE(col, NOW()), ... WHERE pk = $n``
- ``INSERT INTO t (cols) VALUES ($n | 'literal', ...)``

Transactions snapshot the tables and restore them on rollback. ``FakePool``
enforces ``max_size`` so tests catch code that holds a connection while
acquiring another one.
"""
import copy
import re
from contextlib import asynccontextmanager
from datetime import datetime, timezone
from typing import Any

_SELECT = re.compile(
    r"^SELECT (?P<cols>.+?) FROM (?P<table>\S+)(?: WHERE (?P<wcol>\S+) > \$1)?"
    r" ORDER BY (?P<ocol>\S+) LIMIT \$(?P<lim>\d+)$"
)
_UPDATE = re.compile(r"^UPDATE (?P<table>\S+) SET (?P<assign>.+) WHERE (?P<pk>\S+) = \$(?P<n>\d+)$")
_ASSIGN = re.compile(r"(\w+) = (\$\d+|NOW\(\)|COALESCE\((\w+), NOW\(\)\))")
_INSERT = re.compile(r"^INSERT INTO (?P<table>\S+) \((?P<cols>[^)]+)\) VALUES \((?P<vals>.+)\)$")


def _normalize(sql: str) -> str:
    return " ".join(sql.replace('"', "").split())


class FakeDatabase:
    """Tables are lists of dict rows keyed by fully-qualified table name."""

    def __init__(self) -> None:
        self.tables: dict[str, list[dict[str, Any]]] = {}
        self.statements: list[str] = []

    def table(self, name: str) -> list[dict[str, Any]]:
        return self.tables.setdefault(name, [])

    def now(self) -> datetime:
        return datetime.now(timezone.utc)


class FakeTransaction:
    def __init__(self, db: FakeDatabase) -> None:
        self._db = db
        self._snapshot: dict[str, list[dict[str, Any]]] = {}

    async def start(self) -> None:
        self._snapshot = copy.deepcopy(self._db.tables)

    async def commit(self) -> None:
        self._snapshot = {}

    async def rollback(self) -> None:
        self._db.tables = self._snapshot


class FakeConnection:
    def __init__(self, db: FakeDatabase) -> None:
        self._db = db

    def transaction(self) -> FakeTransaction:
        return FakeTransaction(self._db)

    async def fetch(self, sql: str, *args: Any) -> list[dict[str, Any]]:
        stmt = _normalize(sql)
        self._db.statements.append(stmt)
        match = _SELECT.match(stmt)
        if not match:
            raise AssertionError(f"FakeConnection cannot interpret: {stmt}")
        cols = [c.strip() for c in match["cols"].split(",")]
        rows = sorted(self._db.table(match["table"]), key=lambda r: r[match["ocol"]])
        if match["wcol"]:
            rows = [r for r in rows if r[match["wcol"]] > args[0]]
        limit = args[int(match["lim"]) - 1]
        return [{c: row[c] for c in cols} for row in rows[:limit]]

    async def execute(self, sql: str, *args: Any) -> str:
        stmt = _normalize(sql)
        self._db.statements.append(stmt)
        if match := _UPDATE.match(stmt):
            pk_value = args[int(match["n"]) - 1]
            count = 0
            for row in self._db.table(match["table"]):
                if row[match["pk"]] != pk_value:
                    continue
                for column, expr, coalesce_col in _ASSIGN.findall(match["assign"]):
                    if expr.startswith("$"):
                        row[column] = args[int(expr[1:]) - 1]
                    elif expr == "NOW()":
                        row[column] = self._db.now()
                    else:
                        row[column] = row[coalesce_col] or self._db.now()
                count += 1
            return f"UPDATE {count}"
        if match := _INSERT.match(stmt):
            cols = [c.strip() for c in match["cols"].split(",")]
            vals = [v.strip() for v in match["vals"].split(",")]
            row = {}
            for col, val in zip(cols, vals):
                if val.startswith("$"):
                    row[col] = args[int(val[1:]) - 1]
                elif val.upper() == "NULL":
                    row[col] = None
                else:
                    row[col] = val.strip("'")
            self._db.table(match["table"]).append(row)
            return "INSERT 0 1"
        raise AssertionError(f"FakeConnection cannot interpret: {stmt}")


class FakePool:
    """asyncpg-style pool: ``acquire()`` is an async context manager."""

    def __init__(self, db: FakeDatabase, max_size: int = 1) -> None:
        self.db = db
        self.max_size = max_size
        self.in_use = 0

    @asynccontextmanager
    async def _acquire(self):
        if self.in_use >= self.max_size:
            raise RuntimeError("FakePool exhausted (connection held while acquiring another)")
        self.in_use += 1
        try:
            yield FakeConnection(self.db)
        finally:
            self.in_use -= 1

    def acquire(self):
        return self._acquire()


class AwaitablePool:
    """asyncdb-style pool: ``await acquire()`` then ``release(conn)``."""

    def __init__(self, db: FakeDatabase) -> None:
        self.db = db
        self.released = 0

    async def acquire(self) -> FakeConnection:
        return FakeConnection(self.db)

    async def release(self, conn: FakeConnection) -> None:
        self.released += 1
